# Generated by Django 5.2.13 on 2026-04-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0002_customuser_assigned_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('customer', 'Customer'), ('manager', 'Manager'), ('district', 'District'), ('mandalam', 'Mandalam'), ('marketing', 'Marketing')], default='superadmin', max_length=50),
        ),
    ]
