# Generated by Django 5.2.4 on 2026-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0007_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
