# Generated by Django 5.2.4 on 2026-05-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0008_lead_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='count',
        ),
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cyborgapp.lead')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyborgapp.subcategory')),
            ],
        ),
    ]
