# Generated by Django 5.2.4 on 2026-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0010_lead_status_leadupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_level',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('mandalam', 'Mandalam'), ('district', 'District'), ('superadmin', 'Superadmin')], default='marketing', max_length=20),
        ),
    ]
