# Generated by Django 5.2.4 on 2026-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0012_commissionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequirement',
            name='admin_markup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerrequirement',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='admin_markup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='usertype',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('district', 'District'), ('mandalam', 'Mandalam'), ('marketing', 'Marketing')], max_length=20, unique=True),
        ),
    ]
