# Generated by Django 5.2.4 on 2026-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0014_alter_commissionsetting_usertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('superadmin', 'Superadmin'), ('customer', 'Customer'), ('manager', 'Manager'), ('district', 'District'), ('mandalam', 'Mandalam'), ('marketing', 'Marketing')], max_length=20, unique=True)),
                ('superadmin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('district_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mandalam_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
