# Generated by Django 5.2.4 on 2026-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0015_registrationcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
