# Generated by Django 5.2.4 on 2026-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0016_lead_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admin_markup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
