# Generated by Django 5.2.4 on 2026-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0017_lead_admin_markup_lead_customer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='admin_markup',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer_amount',
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Project Sale (to Customer)'), ('commission', 'Project Commission'), ('product_sale', 'Product Sale'), ('district_reg', 'District Registration'), ('mandalam_reg', 'Mandalam Registration'), ('marketer_reg', 'Marketer Registration')], max_length=20),
        ),
    ]
