# Generated by Django 5.2.4 on 2026-05-17 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0019_customuser_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='usertype',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('customer', 'Associate Company'), ('manager', 'Manager'), ('district', 'District Franchise'), ('mandalam', 'Fecilitation Center'), ('marketing', 'Digital Franchise')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('customer', 'Associate Company'), ('manager', 'Manager'), ('district', 'District Franchise'), ('mandalam', 'Fecilitation Center'), ('marketing', 'Digital Franchise')], default='superadmin', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationcommission',
            name='usertype',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('customer', 'Associate Company'), ('manager', 'Manager'), ('district', 'District Franchise'), ('mandalam', 'Fecilitation Center'), ('marketing', 'Digital Franchise')], max_length=20, unique=True),
        ),
    ]
