# Generated by Django 5.2.4 on 2026-05-17 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0020_category_created_by_alter_commissionsetting_usertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
