# Generated by Django 5.2.4 on 2026-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0021_subcategory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
