# Generated by Django 5.2.4 on 2026-05-17 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0022_requirementitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
