# Generated by Django 5.2.4 on 2026-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyborgapp', '0023_alter_leadupdate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
